name: Generate Action Code
description: Generates the action code

runs:
  using: composite
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: package.json
        check-latest: true
        cache: npm
    - name: Generate action code
      shell: bash
      run: |
        npm clean-install
        npm run build
        npm run pack
