name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      node_version:
        description: "Node.js version to use"
        required: false
        default: "24"
      script:
        description: "Script to build/bundle the action"
        required: false
        default: "ncc build lib/main.js -o dist --license license.txt --target es2024"

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write

    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@v1
    with:
      tag: "${{ github.event.inputs.tag }}"
      node_version: ${{ inputs.node_version || '24' }}
      script: ${{ inputs.script || 'ncc build lib/main.js -o dist --license license.txt --target es2024' }}
